### ISSUE TITLE
Community::ServiceQuotas::S3 fails with 'internal failure'

### ISSUE THREAD

**Issue by NickDarvey** [org-formation/aws-resource-providers#104]
## Repro

1. Create a new AWS account
2. Follow the steps in [Community::ServiceQuotas::S3](https://github.com/org-formation/aws-resource-providers/blob/3727b49baf117a701c37a6224b5b02f7774937ed/service-quotas/s3/installation.md#installation-using-aws-cli) to install via the AWS CLI

## Expected

Type is registered.

## Actual

```
❯ aws cloudformation describe-type-registration --registration-token  "f9f2a953-75bf-4fb1-a78f-55091e83f2b4"  --profile Me --region us-east-1
{
    "ProgressStatus": "FAILED",
    "Description": "Deployment is currently in DEPLOY_STAGE of status FAILED\nDeployment failed with error. Error message: [f9f2a953-75bf-4fb1-a78f-55091e83f2b4] Internal Failure",
    "TypeArn": "arn:aws:cloudformation:us-east-1:1234:type/resource/Community-ServiceQuotas-S3",
    "TypeVersionArn": "arn:aws:cloudformation:us-east-1:1234:type/resource/Community-ServiceQuotas-S3/00000001"
}
```

The same occurs via [org-formation](https://github.com/org-formation/aws-resource-providers/blob/3727b49baf117a701c37a6224b5b02f7774937ed/service-quotas/s3/installation.md#installation-using-org-formation-task).

I've tried:
```
aws cloudformation delete-stack --stack-name community-servicequotas-s3-resource-role --profile Me --region us-east-1
```
and following the steps again but reach the same outcome.

**Comment by dalenewman** [comment]
I'm getting the same for registering any of these community organization types.

**Comment by eduardomourar** [comment]
Seems related to this issue here: https://github.com/aws-cloudformation/cloudformation-cli/issues/875

Do you @NickDarvey and @dalenewman mind trying to deploy using the CloudFormation CLI and post any details in that issue, please?

**Comment by dalenewman** [comment]
I don't think there's any more I could add to that issue that isn't already there.  I'm just not provisioning the community organization types for now.  I am creating some new accounts today so I'll let you know if the problem magically resolves itself.

**Comment by NickDarvey** [comment]
>today it worked. 🎉 I even added them back in for the account it didn't work on and it's fine for that account now too.

Same for us. I guess AWS has resolved the issue 🤷

**Comment by sakopov** [comment]
Does anybody know what's actually causing these issues? I opened a support ticket with AWS but they are refusing to look into it because the "internal failure" originates from this library and not a plain CF template. I've been stuck about a week on this and the issue doesn't seem to be resolving itself.

**Comment by OlafConijn** [comment]
hi @sakopov,

the reason for this was that AWS is phasing out the nodejs16 runtime.
you should be able to use the version 1.0.0 of any provider without issues: `community-servicequotas-s3-1.0.0.zip`

hope that helps!
more context on slack: https://join.slack.com/t/org-formation/shared_invite/enQtOTA5NjM3Mzc4ODUwLTMxZjYxYzljZTE5YWUzODE2MTNmYjM5NTY5Nzc3MzljNjVlZGQ1ODEzZDgyMWVkMDg3Mzk1ZjQ1ZjM4MDhlOGM
