### ISSUE TITLE
feature request: block public access to S3 at the account level

### ISSUE THREAD

**Issue by craighurley** [org-formation/aws-resource-providers#11]
Hello,

In a similar way that password policies can be applied to an account or set of accounts, it would be nice if org-formation was able to set "block public access" to S3 at _the account level_.

<img width="1171" alt="Screen Shot 2020-08-13 at 16 24 00" src="https://user-images.githubusercontent.com/3684519/90094288-a0695a00-dd81-11ea-9b99-f92e69731ea9.png">

- https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html#console-block-public-access-options

**Comment by eduardomourar** [comment]
here is the cloudformation coverage related issue: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/168

**Comment by OlafConijn** [comment]
hi @craighurley, that took a fair while :).

I just pushed an example on how to use `Community::S3::PublicAccessBlock` and `Community::Organizations::EbsEncryptionDefaults` from within org-formation.  This will work from version 0.9.10 onwards.

https://github.com/org-formation/org-formation-cli/tree/master/examples/secure-defaults

looking forward to your feedback!
