### ISSUE TITLE
Community::Config::ConformancePack

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#20]
dont have a clear view on what the model should look like yes but, a ConformancePack resource should:
- Allow you to deploy AWS 'sample' templates as well as new templates.
- Allow to deploy conformance packs to the entire AWS Organization.

**Comment by eduardomourar** [comment]
is `Community::Config::ConformancePack` resource similar to [`AWS::Config::ConformancePack`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-conformancepack.html), but for the whole organization?

**Comment by OlafConijn** [comment]
to be honest someone mentioned this would be a cool resource provider (implying there was no AWS CFN type) but indeed there is. There also is [AWS::Config::OrganizationConformancePack](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-organizationconformancepack.html) for organizations. will close for now, thanks for pointing that out :)
