### ISSUE TITLE
Packages contain aws sdk

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#22]
The current build process includes the aws sdk (and all of its dependencies) when packaging a RP.
We should be able to leave the aws sdk out and have a smaller package size.

Downloading/installing will be faster and hosting the registry will cost less money

**Comment by eduardomourar** [comment]
Fixed by using the bootstrap from Lerna. It only installs the AWS SDK in the root of the repository, so it should not add it to the package anymore.

**Comment by eduardomourar** [comment]
i found out what was the problem. during packaging with docker, the .npmrc in the repo root was not being considered. after creating one in each subfolder, the bundled size is a lot smaller.
