### ISSUE TITLE
Define quality gates and link to versioning schema

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#25]
Currently all resource providers are versioned at 0.1.0.
Would be good to have a set of quality gates that can be implemented and reflect in the versioning scheme

Quality gates could be things like: support all methods, unit testing, documentation, review, contract testing.
Quality gates can also be also explicitly discussed, documented and deviated from deviated from.

**Comment by eduardomourar** [comment]
I realized that we will need probably to use GithubFlow (similar to what is suggested here: https://hackernoon.com/a-monorepo-github-flow-and-automation-ftw-c41a2d9c48bb). Github Releases as our source of truth that will be sync automatically to S3 bucket. All of that can be automated in Actions while being triggered by a PR.

**Comment by eduardomourar** [comment]
From the perspective of coverage, we a have minimum set in jest config file and 5% variation allowed by CodeCov (in its configuration).

**Comment by OlafConijn** [comment]
duplicate of #31
