### ISSUE TITLE
Deprecate SAML provider resource

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/aws-resource-providers#76]
AWS has released an [official resource type for IAM SAML providers](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-samlprovider.html). Therefore, we should review our community resource to ser if it is still needed.

**Comment by zaro0508** [comment]
wow, i didn't even know about this until i saw this issue.  hmm, how about we just add documentation that it's deprecated and tell people to use the officially supported ones from AWS?

**Comment by eduardomourar** [comment]
Yes. I just wanted to confirm that it works similarly to current resource provider from the community.

**Comment by zaro0508** [comment]
I just switched from the ofn community one to the official aws one and it worked great for me.  I didn't change my stack name so I did have to delete the existing CFN stack before deploying with AWS saml provider though.  https://github.com/Sage-Bionetworks-IT/testitorgmgnt-infra/blob/master/org-formation/600-access/_tasks.yaml

**Comment by OlafConijn** [comment]
thanks @zaro0508
